invite.invite_type.*:
  type: config_entity
  label: 'Invite Types'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    description:
      type: string
      label: 'Description'
    data:
      type: string
      label: 'Data'
    status:
      type: integer
      label: 'Status'
